// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaS0e9Ap0kER-HOp_irJ4AErOeB2zy3J0',
    appId: '1:231085352974:android:3b4f3fda7646a7f154345f',
    messagingSenderId: '231085352974',
    projectId: 'smartsaver-fb0d2',
    databaseURL: 'https://smartsaver-fb0d2-default-rtdb.firebaseio.com',
    storageBucket: 'smartsaver-fb0d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv_6RFxxITHU0ejqHR0J5yWyI7MSgv-_s',
    appId: '1:231085352974:ios:21f422b974cef65554345f',
    messagingSenderId: '231085352974',
    projectId: 'smartsaver-fb0d2',
    databaseURL: 'https://smartsaver-fb0d2-default-rtdb.firebaseio.com',
    storageBucket: 'smartsaver-fb0d2.appspot.com',
    iosClientId: '231085352974-nps1geh503q2t7fl7gp2oi068og9lpk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}


